print("Welcome to the BMI Calculator")
weight = float(input("Enter your weight (kg): "))
height = float(input("Enter your height (m): "))
BMI = weight / (height ** 2)
print("Your BMI is:", BMI)
print("Thank you for using the BMI Calculator. Come again!")
